version: "3"

services:
  vgldatabase:
    image: postgres:15.1-alpine
    restart: on-failure
    container_name: vgldatabase-nlb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/vgl
    volumes:
      - vgldatabase-nlb:/data/vgl
    ports:
      - ${DB_PORT}:5432

  vglconfig:
    build: ./vglconfig
    image: vglconfig:1.0.9-SNAPSHOT
    restart: on-failure
    container_name: vglconfig-nlb
    environment:
      - GIT_CONFIG_REPOSITORY=${GIT_CONFIG_REPOSITORY}
      - GIT_CONFIG_BRANCH=${GIT_CONFIG_BRANCH:-master}
    ports:
      - ${CONFIG_SERVER_PORT}:8888

  vglservice:
    build: ./vglservice
    image: vglservice:2.6.1-SNAPSHOT
    restart: on-failure
    container_name: vglservice-nlb
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    ports:
      - ${API_SERVER_PORT}:8080
    volumes:
      - ./vglservice/src/main/resources/application.properties:/usr/vglservice/application.properties
    depends_on:
      - vglconfig
      - vgldatabase

  vglfront:
    build: ./vglfront
    image: vglfront:0.5.1-SNAPSHOT
    restart: on-failure
    container_name: vglfront-nlb
    environment:
      - API_URL=${API_URL}
      - TEST_API_URL=${TEST_API_URL_NLB}
    volumes:
      - ./vglfront/src/assets:/usr/share/nginx/html/assets
      - ./vglfront/server/docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FRONT_SERVER_PORT}:80
    depends_on:
      - vglservice

volumes:
  vgldatabase-nlb: